# Generated by Django 5.1.2 on 2025-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='offers/default.jpg', upload_to='destinations/'),
            preserve_default=False,
        ),
    ]
