# Generated by Django 5.1.2 on 2025-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_options_remove_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
